version: '3.9'
services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: poli-eventos-backend
    image: poli-eventos-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: poli-eventos-db
    ports:
      - "3306:3306"
    env_file:
      - ./Server/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./Server/init-sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    container_name: poli-eventos-frontend
    image: poli-eventos-frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:5000/api
      
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
