version: '3.8'
services:
  backend:
    environment:
      DB_HOST: db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    command: ["wait-for-it", "db:3306", "--", "node", "server.js"]
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: poli_eventos_db
      MYSQL_ROOT_PASSWORD: mysqlROOT
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge