version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: poli_eventos_db
      MYSQL_USER: root
      MYSQL_PASSWORD: mysqlROOT
      MYSQL_ROOT_PASSWORD: mysqlROOT
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
